INSERT INTO Profile (title,description) VALUES ('leader','some description');
INSERT INTO Profile (title,description) VALUES ('dev','some description');
INSERT INTO Project (title,description) VALUES ('project 1','some description');
INSERT INTO Project (title,description) VALUES ('project 2','some description');
INSERT INTO Project (title,description) VALUES ('project 3','some description');
INSERT INTO Project (title,description) VALUES ('project 5','some description');
INSERT INTO Celula (title,description) VALUES ('Celula 1','some description');
INSERT INTO Celula (title,description) VALUES ('Celula 2','some description');
INSERT INTO Telephone (number,id_employee) VALUES ('+50431702337',1);
INSERT INTO Employee (firstname, lastname, identification, enrollday, id_celula, id_profile) VALUES ('Jacobo', 'Vasquez', '0801-1987-07418',current_timestamp,1,1);
INSERT INTO Employee (firstname, lastname, identification, enrollday, id_celula, id_profile) VALUES ('Alberto', 'Zuniga', '0801-1987-07419',current_timestamp,1,1);
INSERT INTO Employee (firstname, lastname, identification, enrollday, id_celula, id_profile) VALUES ('Luis', 'Vallecillo', '0801-1987-07420',current_timestamp,1,1);
INSERT INTO Employee_Project (id_employee, id_project, workedhours) VALUES (1,1,10);
INSERT INTO Employee_Project (id_employee, id_project, workedhours) VALUES (2,1,5);
INSERT INTO Employee_Project (id_employee, id_project, workedhours) VALUES (2,2,10);
